name: ldk_flutter
description: Flutter library for LightningDevKit.
version: 0.0.3
homepage: https://github.com/LtbLightning/ldk-flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.49.0
  ffi: ^2.0.1
  freezed_annotation: ^2.1.0
  freezed: ^2.1.0+1
  isolate: ^2.0.3
  path_provider: ^2.0.11
  meta: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  ffigen: ^6.0.1


flutter:
  plugin:
    platforms:
      android:
        package: io.ldk.f.ldk_flutter
        pluginClass: LdkFlutterPlugin
      ios:
        pluginClass: LdkFlutterPlugin

