#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

use crate::r_api::*;
use flutter_rust_bridge::*;

// Section: imports

use crate::types::ChannelInfo;
use crate::types::LdkNodeInfo;

// Section: wire functions

#[no_mangle]
pub extern "C" fn wire_start_ldk(
    port_: i64,
    username: *mut wire_uint_8_list,
    password: *mut wire_uint_8_list,
    host: *mut wire_uint_8_list,
    node_network: *mut wire_uint_8_list,
    path: *mut wire_uint_8_list,
    port: u16,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "start_ldk",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_username = username.wire2api();
            let api_password = password.wire2api();
            let api_host = host.wire2api();
            let api_node_network = node_network.wire2api();
            let api_path = path.wire2api();
            let api_port = port.wire2api();
            move |task_callback| {
                start_ldk(
                    api_username,
                    api_password,
                    api_host,
                    api_node_network,
                    api_path,
                    api_port,
                )
            }
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_get_node_info(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_node_info",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(get_node_info()),
    )
}

#[no_mangle]
pub extern "C" fn wire_open_channel(
    port_: i64,
    pub_key_str: *mut wire_uint_8_list,
    peer_add_str: *mut wire_uint_8_list,
    amount: u64,
    is_public: bool,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "open_channel",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_pub_key_str = pub_key_str.wire2api();
            let api_peer_add_str = peer_add_str.wire2api();
            let api_amount = amount.wire2api();
            let api_is_public = is_public.wire2api();
            move |task_callback| {
                Ok(open_channel(
                    api_pub_key_str,
                    api_peer_add_str,
                    api_amount,
                    api_is_public,
                ))
            }
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_list_channel(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "list_channel",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(list_channel()),
    )
}

#[no_mangle]
pub extern "C" fn wire_list_peers(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "list_peers",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(list_peers()),
    )
}

#[no_mangle]
pub extern "C" fn wire_close_channel(
    port_: i64,
    channel_id_str: *mut wire_uint_8_list,
    peer_pubkey_str: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "close_channel",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_channel_id_str = channel_id_str.wire2api();
            let api_peer_pubkey_str = peer_pubkey_str.wire2api();
            move |task_callback| Ok(close_channel(api_channel_id_str, api_peer_pubkey_str))
        },
    )
}

#[no_mangle]
pub extern "C" fn wire_force_close_channel(
    port_: i64,
    channel_id_str: *mut wire_uint_8_list,
    peer_pubkey_str: *mut wire_uint_8_list,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "force_close_channel",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_channel_id_str = channel_id_str.wire2api();
            let api_peer_pubkey_str = peer_pubkey_str.wire2api();
            move |task_callback| Ok(force_close_channel(api_channel_id_str, api_peer_pubkey_str))
        },
    )
}

// Section: wire structs

#[repr(C)]
#[derive(Clone)]
pub struct wire_uint_8_list {
    ptr: *mut u8,
    len: i32,
}

// Section: wrapper structs

// Section: static checks

// Section: allocate functions

#[no_mangle]
pub extern "C" fn new_uint_8_list_0(len: i32) -> *mut wire_uint_8_list {
    let ans = wire_uint_8_list {
        ptr: support::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    support::new_leak_box_ptr(ans)
}

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        if self.is_null() {
            None
        } else {
            Some(self.wire2api())
        }
    }
}

impl Wire2Api<String> for *mut wire_uint_8_list {
    fn wire2api(self) -> String {
        let vec: Vec<u8> = self.wire2api();
        String::from_utf8_lossy(&vec).into_owned()
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}

impl Wire2Api<u16> for u16 {
    fn wire2api(self) -> u16 {
        self
    }
}

impl Wire2Api<u64> for u64 {
    fn wire2api(self) -> u64 {
        self
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
    fn wire2api(self) -> Vec<u8> {
        unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}

// Section: impl NewWithNullPtr

pub trait NewWithNullPtr {
    fn new_with_null_ptr() -> Self;
}

impl<T> NewWithNullPtr for *mut T {
    fn new_with_null_ptr() -> Self {
        std::ptr::null_mut()
    }
}

// Section: impl IntoDart

impl support::IntoDart for ChannelInfo {
    fn into_dart(self) -> support::DartCObject {
        vec![
            self.channel_id.into_dart(),
            self.funding_txid.into_dart(),
            self.peer_pubkey.into_dart(),
            self.peer_alias.into_dart(),
            self.short_channel_id.into_dart(),
            self.is_channel_ready.into_dart(),
            self.channel_value_satoshis.into_dart(),
            self.local_balance_msat.into_dart(),
            self.available_balance_for_send_msat.into_dart(),
            self.available_balance_for_recv_msat.into_dart(),
            self.channel_can_send_payments.into_dart(),
            self.public.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ChannelInfo {}

impl support::IntoDart for LdkNodeInfo {
    fn into_dart(self) -> support::DartCObject {
        vec![
            self.node_pub_key.into_dart(),
            self.num_channels.into_dart(),
            self.num_usable_channels.into_dart(),
            self.local_balance_msat.into_dart(),
            self.num_peers.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LdkNodeInfo {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

// Section: sync execution mode utility

#[no_mangle]
pub extern "C" fn free_WireSyncReturnStruct(val: support::WireSyncReturnStruct) {
    unsafe {
        let _ = support::vec_from_leak_ptr(val.ptr, val.len);
    }
}
